# Generated by Django 5.2.7 on 2025-11-27 13:22

import app.validators
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProxy',
            fields=[
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, validators=[app.validators.valid_cpf])),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[app.validators.valid_phone])),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=25, null=True)),
                ('complement', models.CharField(blank=True, max_length=200, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=8, null=True, validators=[app.validators.valid_zipcode])),
                ('observations', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('sector', models.CharField(choices=[('Almoxarifado', 'Almoxarifado'), ('Comercial', 'Comercial'), ('Controle', 'Controle'), ('Compras', 'Compras'), ('Contabilidade', 'Contabilidade'), ('Custos', 'Custos'), ('Diretoria', 'Diretoria'), ('Engenharia', 'Engenharia'), ('Financeiro', 'Financeiro'), ('Fiscal', 'Fiscal'), ('Gestão de Pessoas', 'Gestão de Pessoas'), ('Gestão Industrial', 'Gestão Industrial'), ('Industria de Apontamento', 'Industria de Apontamento'), ('Industria de Eletrônicos', 'Industria de Eletrônicos'), ('Industria de Esferas', 'Industria de Esferas'), ('Industria Metalúrgica', 'Industria Metalúrgica'), ('Industria de Placas', 'Industria de Placas'), ('Industria de Tachas', 'Industria de Tachas'), ('Industria de Tintas', 'Industria de Tintas'), ('Jurídico', 'Jurídico'), ('Licitação', 'Licitação'), ('Logística', 'Logística'), ('Manutenção', 'Manutenção'), ('Marketing', 'Marketing'), ('Monitoramentos', 'Monitoramentos'), ('Obras', 'Obras'), ('Projetos', 'Projetos'), ('Qualidade', 'Qualidade'), ('Recebimentos', 'Recebimentos'), ('Recursos Humanos', 'Recursos Humanos'), ('Secretaria', 'Secretaria'), ('Segurança do Trabalho', 'Segurança do Trabalho'), ('Tecnologia', 'Tecnologia'), ('Trânsito', 'Trânsito')], max_length=150)),
                ('metabase_code', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('powerbi_url', models.CharField(blank=True, null=True, unique=True, validators=[app.validators.valid_url])),
                ('status', models.CharField(choices=[('D', 'Em Desenvolvimento'), ('M', 'Em Manutenção'), ('F', 'Em Funcionamento')], default='D', max_length=1)),
                ('fav_by', models.ManyToManyField(blank=True, related_name='favorited_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['sector', 'title'],
                'permissions': [('view_all_dashboards', 'Can view all dashboards')],
            },
        ),
        migrations.AddField(
            model_name='users',
            name='dashboards',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='app.dashboards'),
        ),
        migrations.CreateModel(
            name='GroupDashboards',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.group')),
                ('dashboards', models.ManyToManyField(blank=True, related_name='assigned_groups', to='app.dashboards')),
            ],
        ),
    ]
